### ISSUE TITLE
Shaarli 0.12.1 support

### ISSUE THREAD

**Issue by Br31zh** [ArthurHoaro/code-coloration#5]
Hello,

I’m using Shaarli 0.12.1 and I get the following error when I try to enable your plugin (in v2.1.0): `Class "Shaarli\Router" not found`. Is it a configuration problem on my side, or do your plugin need an update for this version?

Thanks.

**Comment by Br31zh** [comment]
Nevermind, I finally found out that you made modifications since 2.1.0 to support Shaarli 0.12, I downloaded the master branch version, and it’s working now.

**Comment by ArthurHoaro** [comment]
You're right, it looks like I forgot to release a new version.

**Comment by ArthurHoaro** [comment]
:label:  https://github.com/ArthurHoaro/code-coloration/releases/tag/v2.2.0
